gitscrum-community/laravel-gitscrum

.gitignore
app/Http/Controllers/SprintController.php
public/assets/css/style.css
resources/views/sprints/show.blade.php
routes/web.php

Resolvido erro ao tentar excluir uma sprint.

Fix Issue #12 - Erro ao tentar excluir sprint

---

resources/views/layouts/master.blade.php

Resolvido o problema do layout do sistema. Foi alterado somente o layout master. O resultado final pode ser visto na imagem abaixo:

Fix issue #11 - Resolvido problema do layout do sistema

---

app/Http/Controllers/RepositoriesController.php
app/Http/Controllers/UserController.php
resources/views/users/dashboard.blade.php
routes/web.php

#21 - Dashboard performance tweak

---

database/migrations/2016_11_21_160842_create_organizations_table.php

In order to use sqlite database

Remove 'github_id_UNIQUE' from unique()

---

config/database.php

In order to use sqlite databse

Replace :memory: with env('DB_DATABASE'),

---

app/Classes/Github.php
app/Classes/UserClass.php
app/Http/Controllers/Auth/AuthController.php
app/Http/Controllers/WizardController.php
app/Models/Issue.php
app/Models/Organization.php
app/Models/ProductBacklog.php
app/Models/PullRequest.php
app/Models/User.php
app/Observers/CommentObserver.php
app/Observers/IssueObserver.php
database/migrations/2016_12_20_114508_github_id_to_provider_id.php
database/migrations/2016_12_20_153446_create_provider_type_enum.php
resources/views/partials/boxes/repositories.blade.php

So we can reuse the sample field to multiple providers, like GitLab or Bitbucket

Refactoring: change github_id to provider_id

---

app/Classes/Gitlab.php

I've made some checks in gitlab auth provider and adjust when the repo is under a group in gitlab

Resolves issue #95 - Problem when login with gitlab

---

app/Classes/Github.php
app/Classes/Gitlab.php
app/Http/Controllers/WizardController.php

Now all the collaborators are sync in the step 2

Resolves the problem of project members synchronization

---

resources/views/wizard/step2.blade.php

wizard: step2

---

resources/views/wizard/step1.blade.php

wizard: step1

---

resources/views/errors/flash-message.blade.php
resources/views/errors/notification-message.blade.php
resources/views/errors/validation-message.blade.php

this MR is adding closable button in flash notification, so user may close notification without refresh entire page

add closable flash notification

---

resources/lang/id/gitscrum.php

update missing translation in indonesian language

update indonesian translation

---

README.md

+ since we need PHP 7.1 as minimal requirement, we need to update requirement in readme file
+ fix wording

update wording in readme

---

app/Http/Controllers/Web/IssueController.php
resources/views/partials/forms/issue.blade.php

For issue #261 
Signed-off-by: Jonathan O'Brien <jobrien@mstech.com>

Fix for sprint planning index error

---

README.md

Updated instructions to setting up the database and seeders.

Updated the instructions to migrate and seed the database

---

resources/lang/en/gitscrum.php

this pull request fixes the following screen shot exception

Fix missing comma

---

app/Http/Controllers/Web/LabelController.php
resources/views/labels/index.blade.php
resources/views/partials/boxes/label.blade.php
resources/views/partials/lists/labels.blade.php

this pull request will allow to filter the user stories by label  instead of issues only ,  when clicking on label on user story show page

Add filter user stories by label

---

app/Http/Requests/SprintRequest.php
app/Http/Requests/UserStoryRequest.php
resources/lang/en/gitscrum.php

this PR make **product_backlog_id**  required when creating or updating sprint and user story

Modify request files

---

app/Classes/Bitbucket.php
composer.json
database/seeds/DatabaseSeeder.php
database/seeds/DummySeeder.php
database/seeds/SettingSeeder.php

Corrects error `[Symfony\Component\Debug\Exception\FatalThrowableError]  
Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found` when running command `php artisan migrate`

add doctrine/dba for migration, fix database seeder, and fix bitbucket step/2 error

---

composer.json
composer.lock

Update to [`Mockery 1`](https://github.com/mockery/mockery/releases/tag/1.0) [as Laravel](https://github.com/laravel/laravel/blob/master/composer.json#L16).

Update to Mockery 1

---

app/Classes/Bitbucket.php

add validation of object properties in function tplOrganization
error correction when repository is empty
If it fixes an open issue, please link to the issue here (if you write `fixes #num`
or `closes #num`, the issue will be automatically closed when the pull is accepted.)
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.
- [x ] Bug fix (non-breaking change which fixes an issue)
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is …

correction of issue 282: add validation of object properties

---

app/Http/Requests/ProductBacklogRequest.php
resources/lang/ar/gitscrum.php
resources/lang/en/gitscrum.php
routes/web.php

this PR is related to #282 as well ass addition to the fix from #288 , i found that after i login with an empty repository of bitbucket account this exception happens , also i think any product backlog should be related to an organization so that no exception may happen when accessing product-backlogs/list .

Fix storing product backlog

---

resources/lang/en/gitscrum.php
resources/lang/pt/gitscrum.php

Add "you-have" in gitscrum translate file. ( en | pt )
Referencing a nonexistent key: 
https://github.com/gitscrum-community-edition/laravel-gitscrum/blob/9243fedb7d2dbae28092920e935c3b8f72406e95/resources/views/wizard/step1.blade.php#L15

add "gitscrum.you-have" translate

---

resources/views/auth/login.blade.php
resources/views/partials/includes/header.blade.php

Fix link resource by using asset
For dynamic subfolder. if change public folder in some case.
Just change link not effective and asset is function in laravel.
If you're unsure about any of these, don't hesitate to ask. We're here to help!

Fix link resource by using asset

---

composer.json

This **PR** adds whoops as dependency 
to show more beautiful error screen , and improve debugging
If you're unsure about any of these, don't hesitate to ask. We're here to help!

Add whoops

---

app/Classes/Bitbucket.php

Describe your changes in detail.
Why is this change required? What problem does it solve?
Fix issue #229, with this is able get all repositories from bitbucket
After read the documentation bitbucket is able get 100 repositories per page so I only adjust these values  
If you're …

Get all repository from bitbucket

---

resources/views/partials/includes/header.blade.php

fullcalendar isn't included 
the fullcalendar isn't displayed on sprint 'calendar mode'
On my local machine
Before 
If you're unsure about any of these, don't hesitate to ask. We're here to help!

include fullCalendar

---

app/Http/Controllers/Web/IssueController.php
app/Http/Controllers/Web/SprintController.php

Describe your changes in detail.
Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here (if you write `fixes #num`
or `closes #num`, the issue will be automatically closed when the pull is accepted.)
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous …

was bug in line 96 with count

---

app/Classes/Gitea.php
app/Observers/CommentObserver.php

Improved Gitea integration
* use repo name (repo) instead of repo full_name (org/repo) as ProductBacklog title
* fix create/update issue/issue-comment
* fix create new repo when create a new ProductBacklog
tested with self-hosted Gitea 1.2.3
If you're unsure about any of these, don't hesitate to ask. We're here to help!

Improved Gitea integration

---

composer.lock
resources/views/partials/boxes/repositories.blade.php
resources/views/wizard/step1.blade.php

Added Live filter in wizard step 1 page to  filter repo
Added new js Code block to filter repos in wizard page as wanted id #67

Add Live Filter to wizard page 
